# Generated by Django 4.2.3 on 2023-10-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.CharField(default=999, max_length=999),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
