# Generated by Django 4.2.3 on 2023-07-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auctions',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='user',
            name='wishs',
            field=models.ManyToManyField(blank=True, related_name='usersWishs', to='auctions.auctionlisting'),
        ),
    ]
