# Generated by Django 4.2.3 on 2023-07-19 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_user_auctions_user_wishs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishs',
        ),
        migrations.AddField(
            model_name='user',
            name='watchList',
            field=models.ManyToManyField(blank=True, related_name='usersWatchs', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
