# Generated by Django 4.2.3 on 2023-07-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_user_wishs_user_watchlist_alter_bid_auction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
