# Generated by Django 4.2.3 on 2023-07-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('auction', models.ManyToManyField(blank=True, related_name='categorys', to='auctions.auctionlisting')),
            ],
        ),
    ]
