# Generated by Django 4.2.3 on 2023-07-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_category_auction_auctionlisting_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='category',
            new_name='categorys',
        ),
    ]
