# Generated by Django 4.2.3 on 2023-07-25 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_category_auctionlisting_categorys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='categorys',
            new_name='categories',
        ),
    ]
